package menu.sim;

public enum MemberName {
	MICHAEL, DWIGHT, JIM, PAM, ANDY, RYAN, ANGELA, KEVIN, STANLEY, PHYLLIS,
	OSCAR, DARRYL, KELLY, ERIN, MEREDITH, CREED, TOBY, HOLLY, JAN, GABE, 
	WALLACE, CALIFORNIA, JO, KAREN, MINER, ROY, NELLIE, VANCE, PACKER, HANK
}